name: Pull Request

on:
  pull_request:
    branches: ["2.99-openvino"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ðŸ§ª Build snap on amd64
    runs-on: self-hosted
    timeout-minutes: 1440
    steps:
      - name: ðŸ§ª Build snap on amd64
        uses: snapcrafters/ci/test-snap-build@main
